# positionfinder/migrations/0002_auto_20201016_0650.py
# Generated by Django 3.0.3 on 2020-10-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positionfinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chordnotes',
            options={'ordering': ['ordering'], 'verbose_name': 'Tones for Chord', 'verbose_name_plural': 'Tones for Chords'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['ordering', 'note_name'], 'verbose_name': 'Tones for Scale', 'verbose_name_plural': 'Tones for Scales'},
        ),
        migrations.AddField(
            model_name='chordnotes',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
