# positionfinder/migrations/0003_auto_20201121_0602.py
# Generated by Django 3.0.3 on 2020-11-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positionfinder', '0002_auto_20201016_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['category', 'ordering', 'note_name'], 'verbose_name': 'Tones for Scale', 'verbose_name_plural': 'Tones for Scales'},
        ),
    ]
