# Generated by Django 3.0.3 on 2020-11-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positionfinder', '0003_auto_20201121_0602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chordnotes',
            options={'ordering': ['ordering', 'range_ordering'], 'verbose_name': 'Tones for Chord', 'verbose_name_plural': 'Tones for Chords'},
        ),
        migrations.AddField(
            model_name='chordnotes',
            name='range_ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
