# Generated by Django 3.0.3 on 2020-11-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positionfinder', '0004_auto_20201121_0621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chordnotes',
            options={'ordering': ['category', 'ordering', 'range_ordering'], 'verbose_name': 'Tones for Chord', 'verbose_name_plural': 'Tones for Chords'},
        ),
    ]
