# positionfinder/migrations/0006_auto_20201122_0336.py
# Generated by Django 3.0.3 on 2020-11-22 03:36

from django.db import migrations, models
import positionfinder.notes_choices


class Migration(migrations.Migration):

    dependencies = [
        ('positionfinder', '0005_auto_20201121_0622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chordnotes',
            options={'ordering': ['category', 'ordering', 'range_ordering', 'chord_ordering'], 'verbose_name': 'Tones for Chord', 'verbose_name_plural': 'Tones for Chords'},
        ),
        migrations.AddField(
            model_name='chordnotes',
            name='chord_ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chordnotes',
            name='fourth_note',
            field=positionfinder.notes_choices.NotesChoicesField(choices=[(0, 'C'), (1, 'Db/C#'), (2, 'D'), (3, 'Eb/D#'), (4, 'E'), (5, 'F'), (6, 'Gb/F#'), (7, 'G'), (8, 'Ab/G#'), (9, 'A'), (10, 'Bb/A#'), (11, 'B')], default=11, verbose_name='Fourth Tone'),
        ),
        migrations.AlterField(
            model_name='chordnotes',
            name='second_note',
            field=positionfinder.notes_choices.NotesChoicesField(choices=[(0, 'C'), (1, 'Db/C#'), (2, 'D'), (3, 'Eb/D#'), (4, 'E'), (5, 'F'), (6, 'Gb/F#'), (7, 'G'), (8, 'Ab/G#'), (9, 'A'), (10, 'Bb/A#'), (11, 'B')], default=4, verbose_name='Second Note'),
        ),
        migrations.AlterField(
            model_name='chordnotes',
            name='third_note',
            field=positionfinder.notes_choices.NotesChoicesField(choices=[(0, 'C'), (1, 'Db/C#'), (2, 'D'), (3, 'Eb/D#'), (4, 'E'), (5, 'F'), (6, 'Gb/F#'), (7, 'G'), (8, 'Ab/G#'), (9, 'A'), (10, 'Bb/A#'), (11, 'B')], default=7, verbose_name='Third Note'),
        ),
    ]
