# Generated by Django 3.0.3 on 2020-11-22 04:06

from django.db import migrations
import positionfinder.notes_choices


class Migration(migrations.Migration):

    dependencies = [
        ('positionfinder', '0006_auto_20201122_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chordnotes',
            name='fourth_note',
            field=positionfinder.notes_choices.NotesChoicesField(blank=True, choices=[(0, 'C'), (1, 'Db/C#'), (2, 'D'), (3, 'Eb/D#'), (4, 'E'), (5, 'F'), (6, 'Gb/F#'), (7, 'G'), (8, 'Ab/G#'), (9, 'A'), (10, 'Bb/A#'), (11, 'B')], null=True, verbose_name='Fourth Tone'),
        ),
    ]
