# Generated by Django 4.2.4 on 2025-03-31 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positionfinder', '0002_alter_chordnotes_range'),
        ('positionfinder', '0016_remove_vsystem_columns'),
    ]

    operations = [
    ]
