# Generated by Django 5.1.7 on 2025-04-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positionfinder", "0017_merge_20250331_1533"),
    ]

    operations = [
        migrations.AddField(
            model_name="chordnotes",
            name="skip_eight_string_ranges",
            field=models.BooleanField(
                default=False,
                help_text="Skip creation of 8-string ranges for this chord",
            ),
        ),
    ]
