# Generated by Django 5.1.7 on 2025-04-03 17:49

import positionfinder.string_choices
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positionfinder', '0018_chordnotes_highest_string_chordnotes_lowest_string_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chordnotes',
            name='skip_eight_string_ranges',
        ),
    ]
