# Generated by Django 5.1.7 on 2025-04-03 18:01

import positionfinder.chord_position_choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positionfinder', '0019_remove_chordnotes_skip_eight_string_ranges_and_more'),
    ]

    operations = [
        # RemoveField operations removed as they conflict with Django's state tracking
        # due to manual edits in previous migrations.
        # Django should still generate SQL to drop columns based on model state comparison.

        # Original operations from makemigrations
        migrations.AlterModelOptions(
            name='chordnotes',
            options={'ordering': ['ordering', 'chord_ordering', 'range_ordering'], 'verbose_name': 'Chord Note', 'verbose_name_plural': 'Chord Notes'},
        ),
        migrations.AlterModelOptions(
            name='chordposition',
            options={'ordering': ['notes_name'], 'verbose_name': 'Chord Position', 'verbose_name_plural': 'Chord Positions'},
        ),
        migrations.AddField(
            model_name='chordposition',
            name='eighth_note',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chordposition',
            name='eleventh_note',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chordposition',
            name='ninth_note',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chordposition',
            name='seventh_note',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chordposition',
            name='tenth_note',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chordposition',
            name='twelfth_note',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chordposition',
            name='first_note',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chordposition',
            name='inversion_order',
            field=positionfinder.chord_position_choices.ChordInversionChoicesField(choices=[('Basic Position', 'Basic Position'), ('Fifth Inversion', 'Fifth Inversion'), ('First Inversion', 'First Inversion'), ('Fourth Inversion', 'Fourth Inversion'), ('Second Inversion', 'Second Inversion'), ('Sixth Inversion', 'Sixth Inversion'), ('Third Inversion', 'Third Inversion')], default='Basic Position', max_length=20, verbose_name='Inversion Order'),
        ),
    ]
