# Generated by Django 5.1.7 on 2025-04-03 18:06

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('positionfinder', '0020_alter_chordnotes_options_alter_chordposition_options_and_more'),
    ]

    operations = [
        # Manually added RunSQL operations to drop columns directly from the database,
        # bypassing state checks that failed due to previous migration inconsistencies.
        # Operations removed as columns highest_string and lowest_string
        # were already missing from the database schema.
    ]
