# Generated by Django 5.1.7 on 2025-04-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positionfinder', '0021_auto_20250403_1806'), # Depends on the last faked migration
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE positionfinder_chordnotes ALTER COLUMN range TYPE VARCHAR(20);',
            reverse_sql='ALTER TABLE positionfinder_chordnotes ALTER COLUMN range TYPE VARCHAR(8);',
        ),
    ]
