# Generated by Django 5.2 on 2025-04-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positionfinder', '0022_alter_range_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='root',
            name='display_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
